services:
  - type: web
    name: views-generator
    env: docker
    region: oregon
    plan: free
    dockerfilePath: ./Dockerfile
    buildCommand: ""
    startCommand: ""
    envVars:
      - key: DJANGO_SECRET_KEY
        sync: false
